#!/bin/bash

# Get class of a wid
get_class() {
	id=$1
  if [ -z "$id" ]; then
    echo ""
  else
    xprop -id "$id" | sed -n \
      -e '/WM_CLASS/s/\( "\)/\n/g; s/[^\n]*\n\([^"]*\)[^\n]*/\1\n/g' \
      -e '/WM_COMMAND/s/[^"]*/\n\n/1; s/\n"//1; s/\n\([^"]*\)".*/\n\1/; /\n/p' | sed '/^$/d' | head -n1
  fi
}

get_pid() {
	xprop _NET_WM_PID -id "$1" | awk '/[0-9]+/ {print $3}'
}

get_ppid() {
	ps -o ppid= -p $1
}

check_swallowing_process() {
	pid=$(get_pid $1)
	[ -z $pid ] && return 0
	ppid=$(get_ppid $pid)
	gppid=$(get_ppid $(get_ppid $pid))
	ggppid=$(get_ppid $(get_ppid $(get_ppid $pid)))
    
    # Grandparent because gnome-terminal -> bash -> process
	grep -i "^$(ps -o cmd= -p $gppid | awk '{print $1}' | sed 's_^.*/__')$" ~/.config/bspwm/terminals && return 0 
	
    # Grand grandparent because gnome-terminal -> bash -> xdg-open -> process
    # grep -i "^$(ps -o cmd= -p $ggppid | awk '{print $1}' | sed 's_^.*/__')$" ~/.config/bspwm/terminals && return 0 

    # Just parent for pcmanfm
    grep -i "^$(ps -o cmd= -p $ppid | awk '{print $1}' | sed 's_^.*/__')$" ~/.config/bspwm/terminals && return 0
    
    # For lf
    # grep -i "^$(ps -o cmd= -p $pid | awk '{print $1}' | sed 's_^.*/__')$" ~/.config/bspwm/terminals && return 0

    # Don't know what it is
	[ "$(get_ppid "$(get_ppid "$(get_pid "$1")")")" = "$(get_pid "$2")" ] && return 0 || return 1
}

swallow() {
	addedtodesktop=$2
	lasttermdesktop=$(bspc query -D -n last)

	swallowerid=$1
	swallowingid=$(bspc query -N -n last)


	pid=$(get_pid "$swallowerid")
	[ -z $pid ] && return 0
	ppid=$(get_ppid $pid)
	gppid=$(get_ppid $(get_ppid $pid))

    #echo "$pid"
    #echo "$ppid"
    #echo "$gppid"

    #echo $(ps -o cmd= -p $gppid | awk '{print $1}' | sed 's_^.*/__')
    #echo $(ps -o cmd= -p $ppid | awk '{print $1}' | sed 's_^.*/__')
    


	if [ "$addedtodesktop" = "$lasttermdesktop" ] && check_swallowing_process "$swallowerid" "$swallowingid"; then
		((grep -q "^$(get_class "$swallowerid")$" ~/.config/bspwm/noswallow) && 
		(grep -q "^$(get_class "$swallowerid")$" ~/.config/bspwm/terminals)) && return
		grep -i "^$(get_class "$swallowingid")$" ~/.config/bspwm/terminals || return
		echo "$swallowerid $swallowingid" >> /tmp/swallowids
        #echo "$swallowingid" >> /tmp/system-hidden

        #xdo hide "$swallowingid"
		bspc node "$swallowingid" --flag hidden=on 
		#bspc node "$swallowingid" -d I
	fi
}

spit() {
	spitterid=$1
	spitterdesktop=$2
	grep "^$spitterid" /tmp/swallowids || return
	spittingid=$(grep "^$spitterid" /tmp/swallowids | head -n1 | awk '{print $2}')

    #xdo show "$spittingid"


	bspc node "$spittingid" --flag hidden=off

	termdesktop=$(bspc query -D -n "$spittingid")
	[ "$termdesktop" = "$spitterdesktop" ] || bspc node "$spittingid" -d "$spitterdesktop"

	bspc node "$spittingid" -f
	sed -i "/^$spitterid/d" /tmp/swallowids
	#sed -i "/^$spittingid/d" /tmp/system-hidden
}

bspc subscribe node_add node_remove | while read -r event
do
	case $(echo "$event" | awk '{ print $1 }') in
		node_add)
            echo "foo"
            #echo "$event"
            echo $(echo "$event" | awk '{print $5 " " $3}')

            swallow $(echo "$event" | awk '{print $5 " " $3}')
			;;
		node_remove)
            echo "bar"
			spit $(echo "$event" | awk '{print $4 " " $3}')
			;;
	esac
done
