#!/bin/bash

#id=$(xdotool search --limit 1 --classname "audacious") 
#ids=($(xdo id -N "audacious" || xdo id -n "audacious"))

export LD_LIBRARY_PATH="$HOME/local/lib:$LD_LIBRARY_PATH"

get_id() {
    local ids=($(wmctrl -l | awk '/Audacious( \([0-9]+\))?$/ {print $1}'))
    local id="${ids[0]}"
    echo "$id"
}

update_state() {
    echo "$1" > "/tmp/audacious-laststate"
}

update_desk() {
    echo "$(bspc query -D -d focused)" > "/tmp/audacious-lastdesk"
}

unoccupy() {
    random_desk="$(bspc query -D -d any.occupied.\!focused)"
    bspc node "$1" -d "$random_desk"
}

show_node() {
    bspc node "$1" -g hidden=off  --to-desktop focused --focus
    update_state "on"
}

hide_node() {
    bspc node "$1" -g hidden=on 
    update_state "off"
}


id="$(get_id)"

if [ -z "${id}" ]; then
    audacious &
    # sleep .5
    # bspc node -t floating;
    # bspc node -l above

    update_desk 
    update_state "on"

    exit 0;
fi


lastdesk="$(cat "/tmp/audacious-lastdesk")"
laststate="$(cat "/tmp/audacious-laststate")"
currdesk="$(bspc query -D -d focused)"


if [ "$lastdesk" = "$currdesk" ]; then
    if [ "$laststate" = "off" ]; then
        show_node "$id"
    else
        hide_node "$id"
        unoccupy "$id"
    fi
else
    show_node "$id"
    update_desk
fi




