#!/bin/bash

#id=$(xdotool search --limit 1 --classname "audacious") 
#ids=($(xdo id -a 'Telegram (1)'))
#ids=($(wmctrl -l | awk '/Spotify$/ {print $1}'))
#id="${ids[0]}"

#ids=($(wmctrl -l | awk '/Spotify Free$/ {print $1}'))


get_id() {
    local id=$(xdotool search --limit 1 --classname "spotify") 
    echo "$id"
}

update_state() {
    echo "$1" > "/tmp/spotify-laststate"
}

update_desk() {
    echo "$(bspc query -D -d focused)" > "/tmp/spotify-lastdesk"
}

unoccupy() {
    random_desk="$(bspc query -D -d any.occupied.\!focused)"
    bspc node "$1" -d "$random_desk"
}

show_node() {
    bspc node "$1" -g hidden=off  --to-desktop focused --focus
    update_state "on"
}

hide_node() {
    bspc node "$1" -g hidden=on 
    update_state "off"
}


id="$(get_id)"

if [ -z "${id}" ]; then
    LD_PRELOAD=/home/andrey/local/lib/spotify-adblock.so spotify &
    sleep .2
    id="$(get_id)"
    bspc node "$id" -t floating; 
    bspc node "$id" -l above; 

    xdotool windowsize "$id" 800 600;
    xdotool windowmove "$id" 0 170;

    update_desk
    update_state "on"

    exit 0;
fi


lastdesk="$(cat "/tmp/spotify-lastdesk")"
laststate="$(cat "/tmp/spotify-laststate")"
currdesk="$(bspc query -D -d focused)"


if [ "$lastdesk" = "$currdesk" ]; then
    if [ "$laststate" = "off" ]; then
        show_node "$id"
    else
        hide_node "$id"
        unoccupy "$id"
    fi
else
    show_node "$id"
    update_desk
fi



