#!/bin/bash

video_url="$(xclip -selection clipboard -o)"

notify-send -t 3000 "Playing Video" "$video_url";
#mpv  --fs --speed=2.5 --af=rubberband=pitch-scale=0.981818181818181 "$(xclip -o)"
#yt-dlp -f 'bv+ba/b' -o - "$(xclip -o)" - | mpv -
#yt-dlp -o - "$(xclip -selection clipboard -o)" - | mpv -

#yt-dlp --write-auto-sub --write-srt --sub-lang en -o -  | tee /tmp/stream.raw | mpv -

if [[ "$video_url" == *"list"* ]]; then
    mpv --ytdl-format="best[height<=480]" "$video_url";
else 
    mpv --ytdl-format="best[height<=720]" "$video_url";
fi
#
#mpv --ytdl-format=bestvideo+bestaudio/best "$(xclip -selection clipboard -o)" 


