#!/bin/bash


notify-send -t 3000 "Playing HD Video" "$(xclip -selection clipboard -o)";
#mpv --ytdl-format=bestvideo+bestaudio/best --fs --speed=2.5 --af=rubberband=pitch-scale=0.981818181818181 "$(xclip -o)"
#yt-dlp -f 'bv+ba/b' -o - "$(xclip -o)" - | mpv -
#yt-dlp -o - "$(xclip -selection clipboard -o)" - | mpv -

#yt-dlp -f 'bv+ba/b' -o - "$(xclip -selection clipboard -o)" - | mpv -

mpv --ytdl-format=bestvideo+bestaudio/best "$(xclip -selection clipboard -o)" 

